[package]

name = "rust-users"
version = "0.0.1"
authors = [ "Firstname Lastname <you@email.com>" ]

[dependencies]
nickel = "*"
mongodb = "*"
bson = "0.10.0"
rustc-serialize = "*"
serde_json = "1.0"
jwt = "*"
hyper = "*"
rust-crypto = "*"
